import { Primitives } from './Primitives';

export const Colors = {
  light: {
    background: {
      main: {
        primary: Primitives.white_a100,
        secondary: Primitives.gray_50,
        hover: Primitives.gray_100,
        pressed: Primitives.gray_200,
        subtle: Primitives.gray_200,
        neutral: Primitives.gray_100,
        disabled: Primitives.gray_100,
        primary_inverse: Primitives.gray_1000,
        secondary_inverse: Primitives.gray_900,
        neutral_inverse: Primitives.gray_600,
      },
      brand: {
        primary: Primitives.brand_500,
        pressed: Primitives.brand_700,
        hover: Primitives.brand_600,
        selected: Primitives.brand_50,
        subtle: Primitives.brand_100,
        subtle_hover: Primitives.brand_200,
        subtle_pressed: Primitives.brand_300,
      },
      info: {
        primary: Primitives.info_500,
        pressed: Primitives.info_700,
        hover: Primitives.info_600,
        subtle: Primitives.info_100,
        subtle_hover: Primitives.info_200,
        subtle_pressed: Primitives.info_300,
      },
      warning: {
        primary: Primitives.warning_500,
        pressed: Primitives.warning_700,
        hover: Primitives.warning_600,
        subtle: Primitives.warning_100,
        subtle_hover: Primitives.warning_200,
        subtle_pressed: Primitives.warning_300,
      },
      error: {
        primary: Primitives.error_500,
        pressed: Primitives.error_700,
        hover: Primitives.error_600,
        subtle: Primitives.error_100,
        subtle_hover: Primitives.error_200,
        subtle_pressed: Primitives.error_300,
      },
      success: {
        primary: Primitives.success_500,
        pressed: Primitives.success_700,
        hover: Primitives.success_600,
        subtle: Primitives.success_100,
        subtle_hover: Primitives.success_200,
        subtle_pressed: Primitives.success_300,
      },
    },
    text: {
      main: {
        primary: Primitives.gray_1000,
        secondary: Primitives.gray_900,
        tertiary: Primitives.gray_500,
        disabled: Primitives.gray_300,
        primary_inverse: Primitives.gray_50,
        secondary_inverse: Primitives.gray_100,
        tertiary_inverse: Primitives.gray_300,
      },
      brand: {
        primary: Primitives.brand_600,
        pressed: Primitives.brand_800,
        bold: Primitives.brand_700,
        hover: Primitives.brand_700,
        subtle: Primitives.brand_200,
        disabled: Primitives.brand_300,
      },
      info: {
        primary: Primitives.info_500,
        pressed: Primitives.info_800,
        bold: Primitives.info_700,
        hover: Primitives.info_700,
        subtle: Primitives.info_200,
        disabled: Primitives.info_300,
      },
      warning: {
        primary: Primitives.warning_500,
        bold: Primitives.warning_700,
        subtle: Primitives.warning_200,
        disabled: Primitives.warning_300,
      },
      error: {
        primary: Primitives.error_500,
        pressed: Primitives.error_800,
        bold: Primitives.error_700,
        hover: Primitives.error_700,
        subtle: Primitives.error_200,
        disabled: Primitives.error_300,
      },
      success: {
        primary: Primitives.success_500,
        bold: Primitives.success_700,
        subtle: Primitives.success_200,
        disabled: Primitives.success_300,
      },
    },
    border: {
      main: {
        primary: Primitives.gray_400,
        secondary: Primitives.gray_300,
        tertiary: Primitives.gray_100,
        bold: Primitives.gray_600,
        subtle: Primitives.gray_300,
        inverse: Primitives.gray_50,
        disabled: Primitives.gray_200,
      },
      brand: {
        primary: Primitives.brand_600,
        bold: Primitives.brand_700,
        selected: Primitives.brand_500,
        subtle: Primitives.brand_200,
        disabled: Primitives.brand_100,
      },
      info: {
        primary: Primitives.info_500,
        bold: Primitives.info_700,
        subtle: Primitives.info_200,
      },
      warning: {
        primary: Primitives.warning_500,
        bold: Primitives.warning_700,
        subtle: Primitives.warning_200,
      },
      error: {
        primary: Primitives.error_500,
        bold: Primitives.error_700,
        subtle: Primitives.error_200,
      },
      success: {
        primary: Primitives.success_500,
        bold: Primitives.success_700,
        subtle: Primitives.success_200,
      },
    },
    icon: {
      main: {
        primary: Primitives.gray_1000,
        secondary: Primitives.gray_900,
        tertiary: Primitives.gray_500,
        inverse: Primitives.gray_50,
        disabled: Primitives.gray_300,
      },
      brand: {
        primary: Primitives.brand_600,
        pressed: Primitives.brand_800,
        bold: Primitives.brand_700,
        hover: Primitives.brand_700,
        subtle: Primitives.brand_200,
        disabled: Primitives.brand_300,
      },
      info: {
        primary: Primitives.info_500,
        pressed: Primitives.info_800,
        bold: Primitives.info_700,
        subtle: Primitives.info_200,
        disabled: Primitives.info_300,
      },
      warning: {
        primary: Primitives.warning_500,
        pressed: Primitives.warning_800,
        bold: Primitives.warning_700,
        subtle: Primitives.warning_200,
        disabled: Primitives.warning_300,
      },
      error: {
        primary: Primitives.error_500,
        pressed: Primitives.error_800,
        bold: Primitives.error_700,
        subtle: Primitives.error_200,
        disabled: Primitives.error_300,
      },
      success: {
        primary: Primitives.success_500,
        pressed: Primitives.success_800,
        bold: Primitives.success_700,
        subtle: Primitives.success_200,
        disabled: Primitives.success_300,
      },
    },
  },
  dark: {
    background: {
      main: {
        primary: Primitives.gray_1000,
        secondary: Primitives.gray_900,
        hover: Primitives.gray_800,
        pressed: Primitives.gray_700,
        subtle: Primitives.gray_800,
        neutral: Primitives.gray_900,
        disabled: Primitives.gray_900,
        primary_inverse: Primitives.white_a100,
        secondary_inverse: Primitives.gray_50,
        neutral_inverse: Primitives.gray_400,
      },
      brand: {
        primary: Primitives.brand_500,
        pressed: Primitives.brand_200,
        hover: Primitives.brand_300,
        selected: Primitives.brand_900,
        subtle: Primitives.brand_900,
        subtle_hover: Primitives.brand_800,
        subtle_pressed: Primitives.brand_700,
      },
      info: {
        primary: Primitives.info_400,
        pressed: Primitives.info_200,
        hover: Primitives.info_300,
        subtle: Primitives.info_900,
        subtle_hover: Primitives.info_800,
        subtle_pressed: Primitives.info_700,
      },
      warning: {
        primary: Primitives.warning_400,
        pressed: Primitives.warning_200,
        hover: Primitives.warning_300,
        subtle: Primitives.warning_900,
        subtle_hover: Primitives.warning_800,
        subtle_pressed: Primitives.warning_700,
      },
      error: {
        primary: Primitives.error_400,
        pressed: Primitives.error_200,
        hover: Primitives.error_300,
        subtle: Primitives.error_900,
        subtle_hover: Primitives.error_800,
        subtle_pressed: Primitives.error_700,
      },
      success: {
        primary: Primitives.success_400,
        pressed: Primitives.success_200,
        hover: Primitives.success_300,
        subtle: Primitives.success_900,
        subtle_hover: Primitives.success_800,
        subtle_pressed: Primitives.success_700,
      },
    },
    text: {
      main: {
        primary: Primitives.gray_50,
        secondary: Primitives.gray_100,
        tertiary: Primitives.gray_400,
        disabled: Primitives.gray_600,
        primary_inverse: Primitives.gray_1000,
        secondary_inverse: Primitives.gray_800,
        tertiary_inverse: Primitives.gray_600,
      },
      brand: {
        primary: Primitives.brand_400,
        pressed: Primitives.brand_200,
        bold: Primitives.brand_300,
        hover: Primitives.brand_300,
        subtle: Primitives.brand_700,
        disabled: Primitives.brand_700,
      },
      info: {
        primary: Primitives.info_400,
        pressed: Primitives.info_200,
        bold: Primitives.info_300,
        hover: Primitives.info_300,
        subtle: Primitives.info_700,
        disabled: Primitives.info_700,
      },
      warning: {
        primary: Primitives.warning_400,
        bold: Primitives.warning_300,
        subtle: Primitives.warning_700,
        disabled: Primitives.warning_700,
      },
      error: {
        primary: Primitives.error_400,
        pressed: Primitives.error_200,
        bold: Primitives.error_300,
        hover: Primitives.error_300,
        subtle: Primitives.error_700,
        disabled: Primitives.error_700,
      },
      success: {
        primary: Primitives.success_400,
        bold: Primitives.success_300,
        subtle: Primitives.success_700,
        disabled: Primitives.success_700,
      },
    },
    border: {
      main: {
        primary: Primitives.gray_600,
        secondary: Primitives.gray_700,
        tertiary: Primitives.gray_900,
        bold: Primitives.gray_400,
        subtle: Primitives.gray_700,
        inverse: Primitives.gray_1000,
        disabled: Primitives.gray_800,
      },
      brand: {
        primary: Primitives.brand_400,
        bold: Primitives.brand_300,
        selected: Primitives.brand_400,
        subtle: Primitives.brand_700,
        disabled: Primitives.brand_800,
      },
      info: {
        primary: Primitives.info_400,
        bold: Primitives.info_300,
        subtle: Primitives.info_700,
      },
      warning: {
        primary: Primitives.warning_400,
        bold: Primitives.warning_300,
        subtle: Primitives.warning_700,
      },
      error: {
        primary: Primitives.error_400,
        bold: Primitives.error_300,
        subtle: Primitives.error_700,
      },
      success: {
        primary: Primitives.success_400,
        bold: Primitives.success_300,
        subtle: Primitives.success_700,
      },
    },
    icon: {
      main: {
        primary: Primitives.gray_50,
        secondary: Primitives.gray_100,
        tertiary: Primitives.gray_400,
        inverse: Primitives.gray_1000,
        disabled: Primitives.gray_700,
      },
      brand: {
        primary: Primitives.brand_400,
        pressed: Primitives.brand_200,
        bold: Primitives.brand_300,
        hover: Primitives.brand_300,
        subtle: Primitives.brand_700,
        disabled: Primitives.brand_700,
      },
      info: {
        primary: Primitives.info_400,
        pressed: Primitives.info_200,
        bold: Primitives.info_300,
        subtle: Primitives.info_700,
        disabled: Primitives.info_700,
      },
      warning: {
        primary: Primitives.warning_400,
        pressed: Primitives.warning_200,
        bold: Primitives.warning_300,
        subtle: Primitives.warning_700,
        disabled: Primitives.warning_700,
      },
      error: {
        primary: Primitives.error_400,
        pressed: Primitives.error_200,
        bold: Primitives.error_300,
        subtle: Primitives.error_700,
        disabled: Primitives.error_700,
      },
      success: {
        primary: Primitives.success_400,
        pressed: Primitives.success_200,
        bold: Primitives.success_300,
        subtle: Primitives.success_700,
        disabled: Primitives.success_700,
      },
    },
  },
};
